# Generated by Django 4.2.5 on 2023-09-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='itemoptions',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_options', to='cart.cartitem'),
        ),
    ]
