# Generated by Django 4.2.6 on 2023-10-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_itemoptions_created_at_itemoptions_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOptions',
            new_name='ItemOption',
        ),
    ]
