# Generated by Django 4.2.6 on 2023-12-30 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_rename_itemoptions_itemoption"),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS cart_wishlist;'),  # Drop the existing table

        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("product_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="cart",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
