# Generated by Django 4.2.6 on 2023-12-31 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_wishlist_alter_cart_user_id"),
        ("cart", "0006_wishlist"),
    ]

    operations = []
